version: "2"
services:
  db:
      image: mariadb
      container_name: mariadb
      environment:
          - MYSQL_ROOT_PASSWORD=test
          - MYSQL_DATABASE=mateus
      ports:
        - 3306:3306
      volumes:
          - ./data:/var/lib/mysql
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      environment:
          - PMA_ARBITRARY=1
          - PMA_HOST=db
      restart: always
      ports:
          - 8080:80
      volumes:
          - /sessions
      links:
          - db